#!/usr/bin/env python3
"""Validate rollout MP4s generated by run_l1_testing.py.

The checks are intentionally practical for cluster runs:
  - video can be opened and decoded
  - frame count, resolution, and duration are plausible
  - frames are not blank / near-solid color
  - the video is not effectively frozen

This script does not judge task success. It only checks whether the exported
videos are technically usable for inspection.
"""

import argparse
import csv
import json
import os
from pathlib import Path

import imageio
import numpy as np


def _sample_indices(n_frames, max_samples):
    if n_frames <= 0:
        return []
    if n_frames <= max_samples:
        return list(range(n_frames))
    return np.linspace(0, n_frames - 1, max_samples, dtype=int).tolist()


def _probe_metadata(path):
    reader = imageio.get_reader(path, "ffmpeg")
    meta = reader.get_meta_data()
    fps = float(meta.get("fps") or 0.0)
    duration = float(meta.get("duration") or 0.0)
    n_frames = int(meta.get("nframes") or 0)

    size = meta.get("size") or (0, 0)
    if len(size) == 2:
        width, height = int(size[0]), int(size[1])
    else:
        width, height = 0, 0

    # Some ffmpeg/imageio combinations report inf or 0 nframes. Count frames
    # only when metadata is missing so normal runs stay fast.
    if n_frames <= 0 or n_frames > 10**9:
        try:
            n_frames = int(reader.count_frames())
        except Exception:
            n_frames = 0
            for _ in reader:
                n_frames += 1

    if duration <= 0 and fps > 0 and n_frames > 0:
        duration = n_frames / fps

    reader.close()
    return {
        "fps": fps,
        "duration_sec": duration,
        "n_frames": n_frames,
        "width": width,
        "height": height,
    }


def analyze_video(path, args):
    result = {
        "path": str(path),
        "status": "PASS",
        "issues": [],
        "fps": 0.0,
        "duration_sec": 0.0,
        "n_frames": 0,
        "width": 0,
        "height": 0,
        "mean_luma": 0.0,
        "mean_frame_std": 0.0,
        "mean_abs_frame_delta": 0.0,
        "frozen_delta_fraction": 1.0,
    }

    try:
        result.update(_probe_metadata(path))
    except Exception as exc:
        result["status"] = "FAIL"
        result["issues"].append(f"decode_or_metadata_error: {exc}")
        return result

    if result["n_frames"] < args.min_frames:
        result["issues"].append(
            f"too_few_frames: {result['n_frames']} < {args.min_frames}"
        )
    if result["width"] < args.min_width or result["height"] < args.min_height:
        result["issues"].append(
            "resolution_too_small: "
            f"{result['width']}x{result['height']} < "
            f"{args.min_width}x{args.min_height}"
        )
    if result["duration_sec"] < args.min_duration:
        result["issues"].append(
            f"duration_too_short: {result['duration_sec']:.3f}s < {args.min_duration}s"
        )

    sampled = []
    try:
        reader = imageio.get_reader(path, "ffmpeg")
        for idx in _sample_indices(result["n_frames"], args.max_samples):
            frame = reader.get_data(idx)
            if frame.ndim == 2:
                frame = np.repeat(frame[..., None], 3, axis=-1)
            sampled.append(frame[..., :3].astype(np.float32))
        reader.close()
    except Exception as exc:
        result["issues"].append(f"frame_decode_error: {exc}")

    if sampled:
        frame_means = np.array([frame.mean() for frame in sampled], dtype=np.float32)
        frame_stds = np.array([frame.std() for frame in sampled], dtype=np.float32)
        result["mean_luma"] = float(frame_means.mean())
        result["mean_frame_std"] = float(frame_stds.mean())

        if result["mean_luma"] <= args.blank_luma_low:
            result["issues"].append(f"near_black: mean_luma={result['mean_luma']:.2f}")
        if result["mean_luma"] >= args.blank_luma_high:
            result["issues"].append(f"near_white: mean_luma={result['mean_luma']:.2f}")
        if result["mean_frame_std"] <= args.min_frame_std:
            result["issues"].append(
                f"near_solid_color: mean_frame_std={result['mean_frame_std']:.2f}"
            )

        if len(sampled) >= 2:
            deltas = np.array(
                [
                    np.mean(np.abs(sampled[i] - sampled[i - 1]))
                    for i in range(1, len(sampled))
                ],
                dtype=np.float32,
            )
            result["mean_abs_frame_delta"] = float(deltas.mean())
            result["frozen_delta_fraction"] = float(
                np.mean(deltas <= args.frozen_delta_threshold)
            )
            if result["frozen_delta_fraction"] >= args.max_frozen_fraction:
                result["issues"].append(
                    "mostly_frozen: "
                    f"{result['frozen_delta_fraction']:.2f} sampled deltas <= "
                    f"{args.frozen_delta_threshold}"
                )

    if result["issues"]:
        result["status"] = "FAIL"
    return result


def write_csv(path, rows):
    fieldnames = [
        "status",
        "path",
        "issues",
        "n_frames",
        "fps",
        "duration_sec",
        "width",
        "height",
        "mean_luma",
        "mean_frame_std",
        "mean_abs_frame_delta",
        "frozen_delta_fraction",
    ]
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            out = dict(row)
            out["issues"] = "; ".join(out["issues"])
            writer.writerow(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("video_dir", help="Directory containing generated MP4s")
    parser.add_argument("--glob", default="*.mp4", help="Video filename glob")
    parser.add_argument("--report", default=None, help="CSV report path")
    parser.add_argument("--json_report", default=None, help="JSON report path")
    parser.add_argument("--min_frames", type=int, default=20)
    parser.add_argument("--min_duration", type=float, default=1.0)
    parser.add_argument("--min_width", type=int, default=224)
    parser.add_argument("--min_height", type=int, default=224)
    parser.add_argument("--max_samples", type=int, default=48)
    parser.add_argument("--blank_luma_low", type=float, default=5.0)
    parser.add_argument("--blank_luma_high", type=float, default=250.0)
    parser.add_argument("--min_frame_std", type=float, default=4.0)
    parser.add_argument("--frozen_delta_threshold", type=float, default=0.35)
    parser.add_argument("--max_frozen_fraction", type=float, default=0.90)
    args = parser.parse_args()

    video_dir = Path(args.video_dir)
    videos = sorted(video_dir.glob(args.glob))
    if not videos:
        raise SystemExit(f"No videos matched {video_dir / args.glob}")

    rows = [analyze_video(path, args) for path in videos]
    n_fail = sum(row["status"] != "PASS" for row in rows)

    for row in rows:
        issues = " | ".join(row["issues"]) if row["issues"] else "ok"
        print(
            f"[{row['status']}] {row['path']} "
            f"frames={row['n_frames']} size={row['width']}x{row['height']} "
            f"fps={row['fps']:.2f} luma={row['mean_luma']:.1f} "
            f"std={row['mean_frame_std']:.1f} delta={row['mean_abs_frame_delta']:.2f} "
            f"issues={issues}"
        )

    if args.report:
        os.makedirs(os.path.dirname(args.report) or ".", exist_ok=True)
        write_csv(args.report, rows)
        print(f"[report] wrote {args.report}")
    if args.json_report:
        os.makedirs(os.path.dirname(args.json_report) or ".", exist_ok=True)
        with open(args.json_report, "w") as f:
            json.dump(rows, f, indent=2)
        print(f"[report] wrote {args.json_report}")

    print(f"[summary] videos={len(rows)} pass={len(rows) - n_fail} fail={n_fail}")
    raise SystemExit(1 if n_fail else 0)


if __name__ == "__main__":
    main()
